### ISSUE TITLE
Environment variables used in variable values are not evaluated

### ISSUE THREAD

**Issue by YuKitsune** [YuKitsune/plz#31]
When an environment variable is used as part of a variable value, it is not expanded.

Example:
```yaml
commands:
  demo:
    variables:
      path: "$HOME/demo"

    action: 
      sh: echo $path
```

This results in the following being used verbatim in subsequent actions.
```
$HOME/demo
```
